//
// Created by Yasmine Slamani on 11/10/2025.
//

#ifndef OCEANDEPTH_ERROR_CODES_H
#define OCEANDEPTH_ERROR_CODES_H

typedef enum {
    SUCCESS,
    SUCCESS_SATURATED,
    ALREADY_ACTIVE,
    MEMORY_ALLOCATION_ERROR,
    POINTER_NULL,
    INVALID_INPUT,
    UNPROCESSABLE_REQUEST_ERROR,
    INVENTORY_FULL,
    NEW_CELL,
    NEW_ROW,
    NO_UNLOCK_NEEDED,
    WIN,
} ErrorCodes;
#endif //OCEANDEPTH_ERROR_CODES_H